# Form implementation generated from reading ui file 'src/gui/dialog_yes_no.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(492, 216)
        Dialog.setToolTip("")
        Dialog.setAutoFillBackground(False)
        self.no_btn = QtWidgets.QPushButton(Dialog)
        self.no_btn.setGeometry(QtCore.QRect(370, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.no_btn.setFont(font)
        self.no_btn.setToolTip("")
        self.no_btn.setAutoFillBackground(True)
        self.no_btn.setObjectName("no_btn")
        self.yes_btn = QtWidgets.QPushButton(Dialog)
        self.yes_btn.setGeometry(QtCore.QRect(0, 90, 491, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.yes_btn.setFont(font)
        self.yes_btn.setToolTip("")
        self.yes_btn.setObjectName("yes_btn")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 471, 41))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.no_btn.setText(_translate("Dialog", "Non Chui pas sûr à 100%..."))
        self.yes_btn.setText(_translate("Dialog", "OUI"))
        self.textEdit.setHtml(_translate("Dialog", \
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; \
text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; color:#aa0000;\">\
\
Etes-vous bien SÛR ? ( à 100% )\
\
</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
